jester:
  jesterFile: .jester/agents/jester.md
  jesterVersion: v1
  agentFilePattern: '{name}.md'
jesterLoadAlwaysFiles:
  - .jester/data/core.md
  - .jester/data/persona-system.md
  - .jester/workflows/session-save-and-restore.md
  - .jester/workflows/debug-mode.md
  - .jester/workflows/exit.md
  - .memory/.preferences
