

# Jester Persona Settings Template
# This template is used to create the persona-settings.yaml file in .memory/
# Copy this template to .memory/persona-settings.yaml when initializing the system

persona_settings:
  # Current persona preference
  preferred_persona: null  # null = random selection, or specific persona name
  
  # Settings metadata
  created_at: null
  last_modified: null
  version: "1.0"