jester:
  jesterFile: .jester/agents/jester.md
  jesterVersion: v1
  agentFilePattern: '{name}.md'
jesterLoadAlwaysFiles:
  - .jester/data/core.md
memory:
  memoryLocation: .memory
  personaSettings: persona-settings.yaml
  targetAudienceProfiles: target-audience-profiles.yaml
